kind: MutatingWebhookConfiguration
apiVersion: admissionregistration.k8s.io/v1
metadata:
  name: mutating-webhook
webhooks:
  - name: webhook.webhook.svc
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["*"]
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeU1EWXhOekF3TXpBd01Gb1hEVE15TURZeE5EQXdNekF3TUZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTUpDCnZnNDRxUDhCYzNKbzFpVC9uaDJpQkZheVcxTWFSMURnMG5BSkdMSGFEdDIwQXk1OEZhV2kvVHJweEp3a1lxTk8KMW5JWElKK3JhRUdPMUdiRlF6RHpwTitxWVZzNG1KWkFPZkJDWktYVXNXcE5hVi94dVJ5RE1Hc3RMZ20ybkNZcAorMmhybzNUZ0pvdnp3dFQzaWxjZXlZM2h3N1V3aFBBWmhVR2ZMSGhHRmVRUlUybFVHanRZcDRTbTZwRjNlNzl2CkNvbjQ3STNpemhJNXdvL3N2NGVhcU5Gb041bWZmVW9nRzRyajhJbTNsNzZOdnlaQ2lBSnI4S284b2tYckxUUVkKOUVEODBCM1NmZCtIZGN5Ti96NE1PNVpIc2dQcEVZZVVFMkF3MzVsKzhPelBuNFBETU5oU25lVDd6NEVpWkwvZgpxMkRtdlhXZy9ZbjJmaTVrRzZrQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZJT2lkVUZQcTlLZlNtdUFTQUNCelpobGNCM2xNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSEI2Q3RpS3VNbS90SVhKMGhjbgo3ZzhiVnNWdWczc1k3L1FrTTYwUGs5Rks3NnFRdG9PQ0RpREtXMVJsRlJPL0FnMkVGbmVGby93bktKUVRJck1GCnFPREJiMGxqTEtWbzlRZFhQMzlMMTQvNnBkVXRUQkEvZFpkZ0RKbjRUaHVrQ0pHbWg0d3U0dE5yUUJLRDF5blkKVGw0RGFOcFp5RGROa0wrM2NZQk5NVDFEZmZJTlYrL1ByT2NrL0o3aDBFczNMUlM0em8xc0t2QW1CTTUvcW55NwpvSVZMbGh1QlVjb1pvYmFiZmpKQ2dRVXNRdFdEVDhNZEludUhObXgrZkVDZnhmYllZei9ubThBc1l3WTJRODBiCi82UGFzSG9BMmI5YmtNZ3ZSeElvNlVocDZvTlJVanRXNktIaHY4Skx2NE9jV0tBSGh1Skl4cjh6YlFuMTZ3OGMKbUhVPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      service:
        namespace: webhook
        name: webhook
        path: /mutate
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    timeoutSeconds: 5
